services:
  example-game-server:
    image: alpine:latest
    container_name: test-service
    command: ["sh", "-c", "echo Hello, World! && sleep 3600"]
    depends_on:                                         # add these lines to
      curseforge-updater:                               # your server's service          
        condition: service_completed_successfully       # in your docker-compose.yaml

  curseforge-updater:
    # build:                    # uncomment these lines to build locally 
    #   context: ./
    #   dockerfile: Dockerfile
    image: doctor3w/curseforge-updater:latest # comment to build locally
    pull_policy: always # comment to build locally
    container_name: curseforge-updater
    restart: "no"
    volumes:
      - /path/to/your/mods:/mods # change to your mods folder path
    env_file:
      - .env